Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "web_1" do |web|
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "./www_1","/var/www/html"
  config.vm.provision "shell", path: "script.sh"
 end
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "web_2" do |web|
  config.vm.network "forwarded_port", guest: 80, host: 8008
  config.vm.synced_folder "./www_2", "/var/www/html"
  config.vm.provision "shell", path: "script.sh"
 end
end
